### PR TITLE
Send TERM rather than QUIT to Puma cluster

### PR DESCRIPTION
**Pull request by mjtko**
Sending `QUIT` to the Puma cluster brutally murders it, leading to workers dying off with `exit!` when they detect the parent has died.  In turn, this causes `at_exit` handlers to be skipped.

This patch changes `QUIT` for `TERM` for a graceful shutdown:

> `TERM`: send `TERM` to worker. Worker will attempt to finish then exit.

Aside: it could equally use `INT`, but `TERM` seems more descriptive even if it may cause signal handlers to run multiple times as `TERM` is already sent by the dyno manager.  However, code should deal with multiple entries to signal handlers anyway, as the dyno manager does not guarantee that `TERM` is not sent multiple times in any case!

### CODE REVIEW

**Comment by dblock** [comment]
Generally this makes sense. Does it make any sense for this to be configurable?

Can you please update https://github.com/dblock/heroku-forward/blob/master/CHANGELOG.md (add a next release)? 

The build partially failed, this could be unrelated, if you don't mind checking that out, too, please?

**Comment by mjtko** [comment]
Added a changelog entry and allow the signal used to be specified via an option (defaults to `TERM` if not specified).

The build failed cos recent versions of `i18n` and `highline` (installed as a dependency of `jeweler`) don't support the older rubies.  My suggestion would be to also drop support for the older rubies. :)

**Comment by dblock** [comment]
- Rename `termination_signal` to `term_signal` and document in README. 
- Squash your commits.
- Remove old rubies from .travis.yml, I agree.

**Comment by mjtko** [comment]
Renamed, documented, noted, squashed, removed.  As a bonus added `2.1` and `2.2` so we're testing against modern rubies too.

**Comment by dblock** [comment]
Merging. I looked casually into having a test for this, I think it's possible, feel free to PR subsequently.

**Pull request merged**
